name: Reusable Deploy Workflow

on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the deploy-reusable operation
        value: ${{ jobs.reusable-deploy.outputs.outcome }}



jobs:
  reusable-deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: GET CODE
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name}}
      - name: LIST files
        run: ls
      - name: OUTPUT INFORMATION
        run: echo "Deploying & uploading..."
      - name: SET RESULT OUTPUT
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
